### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by christinepham** [christinepham/interview-resources#1]
Update readme with a better description (i.e. repo is about adding in questions that been asked to you this hiring season etc...)

**Comment by rrichajalota** [comment]
So we just need to update readme with content and not interview questions?

**Comment by agdavid** [comment]
Hi Christine, I submitted a PR with a more robust README.  Happy to take feedback.  Let me know if you might need anything else.  Sounds like a great project.

**Comment by christinepham** [comment]
@rrichajalota You can update the interview questions, I just haven't had time to go through them all

**Comment by christinepham** [comment]
@agdavid Thanks! I appreciate the help :)

**Comment by christinepham** [comment]
Tried to give everyone a chance with some of their wording to get it merged! So hopefully that helps out everyone!
